project_name: prometheus-nginxlog-exporter
builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
    goarch:
      - amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - dockerfile: .goreleaser.Dockerfile
    image_templates:
    - quay.io/martinhelmich/prometheus-nginxlog-exporter:latest
    - quay.io/martinhelmich/prometheus-nginxlog-exporter:stable
    - quay.io/martinhelmich/prometheus-nginxlog-exporter:v{{ .Major }}
    - quay.io/martinhelmich/prometheus-nginxlog-exporter:v{{ .Major }}.{{ .Minor }}
    - quay.io/martinhelmich/prometheus-nginxlog-exporter:{{ .Tag }}
    - docker.pkg.github.com/martin-helmich/prometheus-nginxlog-exporter/exporter:latest
    - docker.pkg.github.com/martin-helmich/prometheus-nginxlog-exporter/exporter:stable
    - docker.pkg.github.com/martin-helmich/prometheus-nginxlog-exporter/exporter:v{{ .Major }}
    - docker.pkg.github.com/martin-helmich/prometheus-nginxlog-exporter/exporter:v{{ .Major }}.{{ .Minor }}
    - docker.pkg.github.com/martin-helmich/prometheus-nginxlog-exporter/exporter:{{ .Tag }}
    binaries:
      - prometheus-nginxlog-exporter
    goos: linux
    goarch: amd64
nfpms:
  - vendor: Martin Helmich
    homepage: https://github.com/martin-helmich/prometheus-nginxlog-exporter
    description: Export Prometheus metrics from NGINX (or compatible) log files
    license: Apache 2.0
    maintainer: Martin Helmich <martin@helmich.me>
    formats:
      - deb
      - rpm
    dependencies:
      - systemd
    bindir: /usr/sbin
    files:
      res/package/prometheus-nginxlog-exporter.service: /lib/systemd/system/prometheus-nginxlog-exporter.service
    config_files:
      res/package/default-config.hcl: /etc/prometheus-nginxlog-exporter.hcl
    scripts:
      postinstall: res/package/scripts/postinstall.sh