= NGINX-to-Prometheus log file exporter
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:toc:
:toc-placement!:
:toc-title:

image:https://travis-ci.org/martin-helmich/prometheus-nginxlog-exporter.svg?branch=master[link="https://travis-ci.org/martin-helmich/prometheus-nginxlog-exporter",Build status]
image:https://quay.io/repository/martinhelmich/prometheus-nginxlog-exporter/status[link="https://quay.io/repository/martinhelmich/prometheus-nginxlog-exporter",Docker Repository on Quay]

Helper tool that continuously reads an NGINX log file and exports metrics to https://prometheus.io/[Prometheus].

[discrete]
== Contents

toc::[]

== Usage

You can either use a simple configuration, using command-line flags, or create
a configuration file with a more advanced configuration.

Use the command-line:

    ./nginx-log-exporter \
      -format="<FORMAT>" \
      -listen-port=4040 \
      -namespace=nginx \
      [PATHS-TO-LOGFILES...]

Use the configuration file:

    ./nginx-log-exporter -config-file /path/to/config.hcl

== Collected metrics

This exporter collects the following metrics. This collector can listen on
multiple log files at once and publish metrics in different namespaces. Each
metric uses the labels `method` (containing the HTTP request method) and
`status` (containing the HTTP status code).

- `<namespace>_http_response_count_total` - The total amount of processed HTTP requests/responses.
- `<namespace>_http_response_size_bytes` - The total amount of transferred content in bytes.
- `<namespace>_http_upstream_time_seconds` - A summary vector of the upstream
  response times in seconds. Logging these needs to be specifically enabled in
  NGINX using the `$upstream_response_time` variable in the log format.
- `<namespace>_http_upstream_time_seconds_hist` - Same as `<namespace>_http_upstream_time_seconds`,
  but as a histogram vector. Also requires the `$upstream_response_time` variable
  in the log format.
- `<namespace>_http_response_time_seconds` - A summary vector of the total
  response times in seconds. Logging these needs to be specifically enabled in
  NGINX using the `$request_time` variable in the log format.
- `<namespace>_http_response_time_seconds_hist` - Same as `<namespace>_http_response_time_seconds`,
  but as a histogram vector. Also requires the `$request_time` variable
  in the log format.

Additional labels can be configured in the configuration file (see below).

== Configuration file

You can specify a configuration file to read at startup. The configuration file
is expected to be either in https://github.com/hashicorp/hcl[HCL] or YAML format. Here's an example file:

[source,hcl]
----
listen {
  port = 4040
  address = "10.1.2.3"
}

consul {
  enable = true
  address = "localhost:8500"
  datacenter = "dc1"
  scheme = "http"
  token = ""
  service {
    id = "nginx-exporter"
    name = "nginx-exporter"
    tags = ["foo", "bar"]
  }
}

namespace "app-1" {
  format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\""
  source_files = [
    "/var/log/nginx/app1/access.log"
  ]
  labels {
    app = "application-one"
    environment = "production"
    foo = "bar"
  }
}

namespace "app-2" {
  format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" $upstream_response_time"
  source_files = [
    "/var/log/nginx/app2/access.log"
  ]
}
----

The same file as YAML file:

[source,yaml]
----
listen:
  port: 4040
  address: "10.1.2.3"

consul:
  enable: true
  address: "localhost:8500"
  datacenter: dc1
  scheme: http
  token: ""
  service:
    id: "nginx-exporter"
    name: "nginx-exporter"
    tags: ["foo", "bar"]

namespaces:
  - name: app-1
    format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\""
    source_files:
      - /var/log/nginx/app1/access.log
    labels:
      app: "application-one"
      environment: "production"
      foo: "bar"
  - name: app-2
    format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" $upstream_response_time"
    source_files:
      - /var/log/nginx/app2/access.log
----

Experimental features
---------------------

The exporter contains features that are currently experimental and may change without prior notice.
To use these features, either set the `-enable-experimental` flag or add a `enable_experimental` option
to your configuration file.

### Dynamic re-labeling

Re-labeling lets you add arbitrary fields from the parsed log line as labels to your metrics.
To add a dynamic label, add a `relabel` statement to your configuration file:

[source,hcl]
----
namespace "app-1" {
  // ...

  relabel "host" {
    from = "server_name"
    whitelist = [
      "host-a.com",
      "host-b.de"
    ]
  }
}
----

The `whitelist` property is optional; if set, only the supplied values will be added as label.
All other values will be subsumed under the `"other"` label value. See #16 for a more detailed
discussion around the reasoning.

Dynamic relabeling also allows you to aggregate your metrics by request path (which replaces
the experimental feature originally introduced in #23):

[source,hcl]
----
namespace "app-1" {
  // ...

  relabel "request_uri" {
    from = "request"
    split = 2

    match "^/users/[0-9]+" {
      replacement = "/users/:id"
    }

    match "^/profile" {
      replacement = "/profile"
    }
  }
}
----

Running the collector
---------------------

### Systemd

You can find an example unit file for this service [in this repository](systemd/prometheus-nginxlog-exporter.service). Simply copy the unit file to `/etc/systemd/system`:

    $ wget -O /etc/systemd/system/prometheus-nginxlog-exporter.service https://raw.githubusercontent.com/martin-helmich/prometheus-nginxlog-exporter/master/systemd/prometheus-nginxlog-exporter.service
    $ systemctl enable prometheus-nginxlog-exporter
    $ systemctl start prometheus-nginxlog-exporter

The shipped unit file expects the binary to be located in `/usr/local/bin/prometheus-nginxlog-exporter` and the configuration file in `/etc/prometheus-nginxlog-exporter.hcl`. Adjust to your own needs.

### Docker

You can also run this exporter from the Docker image `quay.io/martinhelmich/prometheus-nginxlog-exporter`:

    $ docker run --name nginx-exporter -v logs:/mnt/nginxlogs -p 4040:4040 quay.io/martinhelmich/prometheus-nginxlog-exporter mnt/nginxlogs/access.log

Command-line flags and arguments can simply be appended to the `docker run` command, for example to use a
configuration file:

    $ docker run --name nginx-exporter -p 4040:4040 -v logs:/mnt/nginxlogs -v /path/to/config.hcl:/etc/prometheus-nginxlog-exporter.hcl quay.io/martinhelmich/prometheus-nginxlog-exporter -config-file /etc/prometheus-nginxlog-exporter.hcl

Credits
-------

- https://github.com/hpcloud/tail[tail], MIT license
- https://github.com/satyrius/gonx[gonx], MIT license
- https://github.com/prometheus/client_golang[Prometheus Go client library], Apache License
- https://github.com/hashicorp/hcl[HashiCorp configuration language], Mozilla Public License
