enable_experimental: true

listen:
  port: 4040

namespaces:
  - name: test
    format: "foo"
    source_files:
      - .behave-sandbox/access.log
  - name: test2
    format: "bar"
    source_files:
      - .behave-sandbox/access2.log