enable_experimental: true

listen:
  port: 4040

namespaces:
  - name: test
    format: "$server_name $remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" $request_time \"$upstream_response_time\" $pipe $ssl_protocol/$ssl_cipher $request_id $host"
    source_files:
      - .behave-sandbox/access.log